spring:
  application:
    name: auth-server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/raze_auth_server?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Karachi&allowPublicKeyRetrieval=true
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:root}
  flyway:
    baseline-on-migrate: true # useful when introducing Flyway to an existing project and need to establish a baseline version to start tracking future migrations.
    baseline-description: <<Flyway Baseline>> # documentation and logging purposes.
    enabled: true # If set to false, Flyway will be disabled and no migrations will be applied
    locations: classpath:db/migration # locations to scan for migration scripts.
    validate-on-migrate: true # validate the applied migrations against the ones available on the classpath.
    fail-on-missing-locations: true # ensures that Flyway fails if one of the specified migration script locations does not exist.

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: debug
    org.springframework.security.oauth2: debug

