server:
  port: 8080

spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gateway-auth-server?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: ${MYSQL_USERNAME:root}  # modify username
    password: ${MYSQL_PASSWORD:root}  # modify password
  flyway:
    baseline-on-migrate: true
    baseline-description: <<Flyway Baseline>>
    enabled: true
    locations: classpath:db/migration
    validate-on-migrate: true
    fail-on-missing-locations: true
logging:
  level:
    root: INFO
    org.springframework.web: debug
    org.springframework.security: debug
    org.springframework.security.oauth2: debug
    org.springframework.cloud.gateway: debug


